export const mealOptions = [
	{ name: 'Spaghetti' },
	{ name: 'Tacos' },
	{ name: 'Chicken Alfredo' },
	{ name: 'Burger and Fries' },
	{ name: 'Chili' },
	{ name: 'Paninis' },
	{ name: 'Taco Gnocchi' },
	{ name: 'Chicken & Gnocchi Soup' },
	{ name: 'Meatball Subs' },
	{ name: 'Beef Tacos' },
	{ name: 'Chinese Takeout' },
	{ name: 'Chicken Parmesan' },
	{ name: 'Pancakes' },
	{ name: 'Biscuits & Gravy' },
	{ name: 'Omelettes & Hashbrowns' },
	{ name: 'Pizza' },
	{ name: 'Sushi Roll' },
	{ name: 'McDonalds' },
	{ name: 'Baked Ziti' },
	{ name: 'Steaks' },
	{ name: 'Cinnamon Rolls' },
];
